name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Usa il branch main per il deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Non è necessario alcun processo di build se hai solo file HTML
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main  # Usa il branch main
        publish_dir: ./  # La directory con i file del sito (ad esempio './', o './docs')
