name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O il ramo che utilizzi per il deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js (se il tuo sito utilizza Node.js)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Cambia questo comando in base alla tua configurazione di build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # La directory di output generata dopo la build (modifica in base al tuo progetto)
